### ISSUE TITLE
运行出错了

### ISSUE THREAD

**Issue by HIT-Ygq** [ZikangYuan/kitti-360_2bag#1]
![erro](https://user-images.githubusercontent.com/90457565/231373717-b9390fdb-548a-4019-a0ee-4572a31cd4ad.png)

十分出色的工作，但我运行之后，出错了，另外，你这个是否可以将IMU融合到bag中呢

**Comment by ZikangYuan** [comment]
抱歉，我忘记了，ROS的pkg命名是不能加"-"的，也不能用大写的英文字母，因此出了问题，我修改一下就好。

**Comment by ZikangYuan** [comment]
好了，问题已解决，您重新download一下，现在应该能直接运行了。

**Comment by HIT-Ygq** [comment]
![2](https://user-images.githubusercontent.com/90457565/231419539-82ff8a70-39b9-4691-9a67-bbcb607a524b.png)

非常感谢，但运行一段后，崩了。

**Comment by ZikangYuan** [comment]
你看看原因，报错原因是变量left_image.empty()，说明index为76的那张图片不在路径下，请检查一下相应数据是否存在，如果存在，是否已损坏。

**Comment by HIT-Ygq** [comment]
是的，第77张图片损坏了。于是我将image1的图片替换了image0中的图片，居然可以运行。但运行一段时间后，还是蹦了。
![3](https://user-images.githubusercontent.com/90457565/231487246-d735b748-9c99-4835-bfa7-ac8359c40509.png)

**Comment by ZikangYuan** [comment]
很遗憾，我在自己的环境下运行的时候，没有遇到上述问题，也没有处理过上述问题的经验。这个问题可能需要靠您自己解决一下。
